version: 3

tasks:
  lint:
    desc: "Lint TypeScript code in api, and db"
    cmds:
      - |
        echo "Linting all packages in parallel"
        cd packages/api && bun run lint & \
        cd packages/db && bun run lint & \
        cd packages/web && bun run lint & \
        wait
      
  lint:fix:
    desc: "Lint and fix TypeScript code in api, db"
    cmds:
      - |
        echo "Linting all packages in parallel"
        cd packages/api && bun run lint:fix & \
        cd packages/db && bun run lint:fix & \
        cd packages/web && bun run lint:fix & \
        wait
      
  db:generate-migrations:
    desc: "Generate database migrations"
    dir: packages/db
    cmds:
      - bun run drizzle-kit generate

  db:migrate:
    desc: "Migrate the database"
    dir: packages/db
    cmds:
      - bun run drizzle-kit migrate

  docker:start:
    desc: "Start docker containers"
    cmds:
      - docker compose up -d --wait

  docker:stop:
    desc: "Stop docker containers"
    cmds:
      - docker compose down

  docker:destroy:
    desc: "Destroy docker containers"
    cmds:
      - docker compose down -v

  docker:reset:
    desc: "Destroy and start docker containers, and apply migrations"
    cmds:
      - |
        echo "Installing dependencies"
        bun i
      - task: docker:destroy
      - task: docker:start
      - task: db:migrate

  start:
    desc: "Start the core services of the project, in parallel"
    cmds:
      - |
        echo "Installing dependencies"
        bun i

      - |
        echo "Checking to see if .env files exist"
        # files are in packages/api, packages/db, and packages/web
        if [ ! -f packages/api/.env ]; then
          echo "Creating .env file in packages/api"
          cp packages/api/.env.example packages/api/.env
        fi
        if [ ! -f packages/db/.env ]; then
          echo "Creating .env file in packages/db"
          cp packages/db/.env.example packages/db/.env
        fi
        if [ ! -f packages/web/.env.local ]; then
          echo "Creating .env.local file in packages/web"
          cp packages/web/.env.example packages/web/.env.local
        fi

      - |
        echo "Applying migrations to the database"
      - task: db:migrate
      - |
        bunx concurrently --restart-tries 99999999 --restart-after 1000 \
         "cd packages/api && bun run dev" \
         "cd packages/db && bun run drizzle-kit studio --port 8082" \
         "cd packages/web && bun run dev"
